//
//  JsonKeys.swift
//  MusicPimp
//
//  Created by Michael Skogberg on 23/05/15.
//  Copyright (c) 2015 Skogberg Labs. All rights reserved.
//

import Foundation
class JsonKeys {
    static let
    TITLE = "title",
    FOLDER = "folder",
    FOLDERS = "folders",
    TRACKS = "tracks",
    ID = "id",
    ARTIST = "artist",
    ALBUM = "album",
    SIZE = "size",
    DURATION = "duration",
    PATH = "path",
    VERSION = "version",
    CMD = "cmd",
    PLAY = "play",
    PAUSE = "pause",
    STOP = "stop",
    SEEK = "seek",
    NEXT = "next",
    PREV = "prev",
    SKIP = "skip",
    VALUE = "value",
    RESUME = "resume",
    TRACK = "track",
    STATE = "state",
    MUTE = "mute",
    POSITION = "position",
    VOLUME = "volume",
    PLAYLIST = "playlist",
    PLAYLISTS = "playlists",
    PLAYLIST_INDEX = "playlist_index",
    INDEX="index",
    ADD = "add",
    REMOVE = "remove",
    DELETE = "delete",
    Move = "move",
    From = "from",
    To = "to",
    ERROR = "error",
    EVENT = "event",
    TIME_UPDATED = "time_updated",
    TRACK_CHANGED = "track_changed",
    PLAYSTATE_CHANGED = "playstate_changed",
    PLAYLIST_MODIFIED = "playlist_modified",
    INDEX_CHANGED = "playlist_index_changed",
    MUTE_TOGGLED = "mute_toggled",
    VOLUME_CHANGED = "volume_changed",
    WELCOME = "welcome",
    PING = "ping",
    STATUS = "status",
    NAME = "name",
    CREATED = "created",
    JOB = "job",
    WHEN = "when",
    Hour = "hour",
    Minute = "minute",
    Days = "days",
    Enabled = "enabled",
    Save = "save",
    Ap = "ap",
    ApnsAdd = "apns_add",
    ApnsRemove = "apns_remove",
    ApnsTag = "tag",
    Id = "id"
}
